# fly.toml file generated for byte-air on 2023-03-25T14:19:42-04:00

app = "byte-air"
kill_signal = "SIGTERM"
kill_timeout = 5
primary_region = "iad"

[experimental]
  auto_rollback = true

[env]
  DATABASE_PATH = "/data/byte_air_data/byte_air_prod.db"
  PHX_HOST = "byte-air.fly.dev"
  PORT = "8080"

[mounts]
  source = "byte_air_data"
  destination = "/data"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
